FROM alpine:latest

ARG NETWORK_IP

RUN mkdir -p /tftpboot/efi64
RUN chmod -R 555 /tftpboot

RUN apk add --no-cache --update dnsmasq curl

RUN mv /etc/dnsmasq.conf /etc/dnsmasq.conf.bak

RUN touch /etc/dnsmasq.conf
RUN echo "port=0 # Disable DHCP/DNS service" >> /etc/dnsmasq.conf
RUN echo "dhcp-range=${NETWORK_IP},proxy" >> /etc/dnsmasq.conf
RUN echo "dhcp-boot=pxelinux.0" >> /etc/dnsmasq.conf
RUN cd /tftpboot \
    && curl -O https://boot.netboot.xyz/ipxe/netboot.xyz.kpxe
RUN echo 'pxe-service=x86PC, "Boot BIOS PXE", netboot.xyz.kpxe' >> /etc/dnsmasq.conf
RUN cd /tftpboot/efi64 \
    && curl -O https://boot.netboot.xyz/ipxe/netboot.xyz.efi
RUN echo 'pxe-service=BC_EFI, "Boot UEFI PXE-BC", efi64/netboot.xyz.efi' >> /etc/dnsmasq.conf
RUN echo 'pxe-service=x86-64_EFI, "Boot UEFI PXE-64", efi64/netboot.xyz.efi' >> /etc/dnsmasq.conf
RUN echo "enable-tftp" >> /etc/dnsmasq.conf
RUN echo "tftp-root=/tftpboot" >> /etc/dnsmasq.conf
RUN echo "user=root # Solve: operation not permitted" >> /etc/dnsmasq.conf

RUN echo "DNSMASQ_EXCEPT=lo" >> /etc/conf.d/dnsmasq

EXPOSE 69/udp

CMD ["/usr/sbin/dnsmasq", "-k"]
